fix(TBD-11046): Kafka spark big data streaming doesn't work well(missing dependencies)
Talend/tbd-studio-se pull request #1609
Opened 2020-09-09 08:41 UTC by sponomarova

…sing dependencies in hdp 2.x) (#1564)

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2020-09-09 09:21 UTC, lbourgeois approved these changes
LGTM

2020-09-14 10:11 UTC, AlixMetivier approved these changes

2020-09-14 10:12 UTC, AlixMetivier requested changes

2020-09-14 10:12 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
> +      "childNodes" : [ {
where is the [ closed at ?

2020-09-14 11:31 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
> +      }, {
```
      }, {
      "childNodes" : [ {
        "childNodes" : [ ],
        "id" : "DYNAMIC_HDP_2_6_0_3_8_kafka_2_11_0_10_0_1_jar",
        "tagName" : "library"
      }, {
        "childNodes" : [ ],
        "id" : "DYNAMIC_HDP_2_6_0_3_8_spark_streaming_kafka_0_10_2_11_2_1_0_2_6_0_3_8_jar",
        "tagName" : "library"
      }, {
        "childNodes" : [ ],
        "id" : "DYNAMIC_HDP_2_6_0_3_8_kafka_clients_0_10_1_2_6_0_3_8_jar",
        "tagName" : "library"
      }, {
        "childNodes" : [ ],
        "id" : "DYNAMIC_HDP_2_6_0_3_8_lz4_1_3_0_jar",
        "tagName" : "library"
      }, {
        "childNodes" : [ ],
        "id" : "DYNAMIC_HDP_2_6_0_3_8_slf4j_api_1_7_21_jar",
        "tagName" : "library"
      },
````

2020-09-14 11:32 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
> +      }, {
@lbourgeois how do you do suggestions, can't make it work :(

2020-09-14 11:34 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdp2xx/Hortonworks_HDP_2_6_0_3_8.json
>          "childNodes" : [ ],
```suggestion
      }, {
      "childNodes" : [ {
        "childNodes" : [ ],
        "id" : "DYNAMIC_HDP_2_6_0_3_8_kafka_2_11_0_10_0_1_jar",
        "tagName" : "library"
      }, {
        "childNodes" : [ ],
        "id" : "DYNAMIC_HDP_2_6_0_3_8_spark_streaming_kafka_0_10_2_11_2_1_0_2_6_0_3_8_jar",
        "tagName" : "library"
      }, {
        "childNodes" : [ ],
```

2020-09-14 12:13 UTC, AlixMetivier approved these changes

2020-09-17 18:42 UTC, merged