TBD-11039 : Dataproc Spark job fails with java.lang.NoSuchMethodError
Talend/tbd-studio-se pull request #1623
Opened 2020-09-18 17:12 UTC by firefryy

…starting

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2020-09-21 07:01 UTC, Redwene commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    id="google-cloud-storage-1.2.1"
why did you downgrade the version ?

2020-09-21 07:30 UTC, firefryy commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    id="google-cloud-storage-1.2.1"
hive-exec jar (which we can not change) use a lower guava version of those jars so we have a nosuchmethod issue, so i had to downgrade the version of those jars

2020-09-21 13:36 UTC, Redwene approved these changes
lgtm

2020-09-23 15:02 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    id="google-cloud-storage-1.2.1"
Have you checked that guava versions used by hive-exec and google-cloud-storage-1.2.1 are the same ?

2020-09-24 12:40 UTC, firefryy commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    id="google-cloud-storage-1.2.1"
they cannot be the same, guava 14 (the version of hive-exec version) is older than all version of google-sloud-storage dependencies, i took the older which is still compatible with it

2020-09-25 07:34 UTC, lbourgeois approved these changes
LGTM

2020-11-05 08:52 UTC, lbourgeois submitted a review, later dismissed
LGTM

2020-11-05 08:53 UTC, lbourgeois commented
build-patch

2020-11-06 11:20 UTC, Redwene requested changes

2020-11-06 11:20 UTC, Redwene commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    mvn_uri="mvn:com.google.guava/guava/19.0">
cve exist on this jar

2020-11-06 11:23 UTC, Redwene commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    mvn_uri="mvn:com.google.guava/guava/19.0">
@lbourgeois

2020-11-06 11:54 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    mvn_uri="mvn:com.google.guava/guava/19.0">
@firefryy Can you confirm that this version with CVE is on cluster side ? Maybe they updated it and then we can do the same.

2020-11-06 13:26 UTC, firefryy commented on main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
> +		    mvn_uri="mvn:com.google.guava/guava/19.0">
yes it's the version on cluster side and if we updated we may have some conflict

2020-11-06 15:02 UTC, Redwene approved these changes

2020-11-09 17:08 UTC, AlixMetivier commented
build-patch

2020-11-13 10:44 UTC, firefryy commented
build-patch

2020-11-13 15:11 UTC, Redwene approved these changes
LGTM

2021-06-07 06:46 UTC, closed without merging