fix(TBD-11382): Inconsistent behavior of job execution for EMR 5.29
Talend/tbd-studio-se pull request #1651
Opened 2020-10-07 15:35 UTC by sponomarova

…upgrade jersey libs

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2020-10-09 14:10 UTC, lbourgeois submitted a review, later dismissed
LGTM

2020-11-04 15:24 UTC, AlixMetivier submitted a review, later dismissed

2020-11-04 17:30 UTC, CarlosTalend requested changes

2020-11-04 17:30 UTC, CarlosTalend commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +            libraries="avro-1.8.2.jar;commons-cli-1.2.jar;commons-collections-3.2.2.jar;commons-configuration-1.6.jar;commons-io-2.4.jar;commons-lang-2.6.jar;commons-logging-1.1.3.jar;emr-metrics-cli
why is jersey-client kept as 1.9?

2020-11-04 17:30 UTC, CarlosTalend commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +            libraries="avro-1.8.2.jar;commons-cli-1.2.jar;commons-collections-3.2.2.jar;commons-configuration-1.6.jar;commons-io-2.4.jar;commons-lang-2.6.jar;commons-logging-1.1.3.jar;emr-metrics-cli
Also in lines 893-895, 905-907, 1939, 2390, and 2404 (even if MapReduce isn't supported)

2020-11-05 08:41 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +             <library id="jersey-client-2.22.2.jar"/>
I think https://github.com/Talend/tbd-studio-se/blob/b41dd714e1d8ac816075d8394754ea52137eb066/main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml#L903 libraryNeeded can be removed

2020-11-05 15:55 UTC, sponomarova commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +            libraries="avro-1.8.2.jar;commons-cli-1.2.jar;commons-collections-3.2.2.jar;commons-configuration-1.6.jar;commons-io-2.4.jar;commons-lang-2.6.jar;commons-logging-1.1.3.jar;emr-metrics-cli
Agree. Will modify that.

2020-11-05 15:56 UTC, sponomarova commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +             <library id="jersey-client-2.22.2.jar"/>
@lbourgeois could you, please explain a little bit? 
I didn't get why <libraryNeeded in line 903 has to be removed. Thanks.

2020-11-05 16:33 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +             <library id="jersey-client-2.22.2.jar"/>
Sorry I meant all the libraryNeeded block containing jersey-core-1.9.jar as it is no longer used

2020-11-12 08:23 UTC, closed without merging