fix(TBD-11038): The distribution AMAZON_EMR with the version APACHE_2_4_0_EMR doesn't exist
Talend/tbd-studio-se pull request #1652
Opened 2020-10-08 12:57 UTC by cbadillo1603

…2_4_0_EMR doesn't exist

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2020-10-09 01:56 UTC, amedvedenko requested changes
left a couple of comments, other changes are good.

2020-10-09 01:56 UTC, amedvedenko commented on main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ComponentType.java
> +            String versionParameter, String versionRepositoryValueParameter, List<String> componentLists) {
doc is missing

2020-10-09 01:56 UTC, amedvedenko commented on main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ComponentType.java
> +        this.mComponentList = componentLists;
I suggest doing a copy of input list to be safe

2020-10-09 01:56 UTC, amedvedenko commented on main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ComponentType.java
> +    }
it's enum, application-level constant. Please remove setter. IMO all variables in enums must be final or, at least, API mustn't allow modifying it outside in any way.

2020-10-09 01:56 UTC, amedvedenko commented on main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ComponentType.java
> +        return mComponentList;
please return copy of the list, to avoid modifications outside of the class

2020-10-09 01:56 UTC, amedvedenko commented on main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ComponentType.java
> +
please put it before the constructor you're referring to

2020-10-09 01:56 UTC, amedvedenko commented on main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ComponentType.java
> +    private List<String> mComponentList;
if it's possible, please, put variables in this enum before the constructors.

2020-10-09 07:43 UTC, cbadillo1603 commented on main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/ComponentType.java
> +        this.mComponentList = componentLists;
Great suggestion, done.

2020-10-09 07:46 UTC, amedvedenko submitted a review, later dismissed

2020-10-13 13:51 UTC, CarlosTalend approved these changes
Some old distributions are modified but they must not be tested

2020-11-19 08:02 UTC, merged