TDI-44985 : treat __DOLLARS__
Talend/tbd-studio-se pull request #1679
Opened 2020-10-20 11:19 UTC by clesaec

https://jira.talendforge.org/browse/TDI-44985

**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [x] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

ObjectId on source are transform to String on target.

**What is the new behavior?**
When precise "__DOLLARS__oid on target data, it transform to ObjectId

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2020-10-20 12:45 UTC, Voievidko submitted a review, later dismissed
LGTM

2020-10-29 08:27 UTC, ypiel-talend requested changes

2020-10-29 08:27 UTC, ypiel-talend commented on main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
> +			     .replace("__DOLLARS__", "$"); // to manage $oid on mongo db side.
Please ask for a single __DOLLAR__

2020-10-30 07:40 UTC, ypiel-talend approved these changes
LGTM

2020-10-30 08:31 UTC, merged