feat(TBD-11264): support Extended Assume Role on CDP 7.1
Talend/tbd-studio-se pull request #1771
Opened 2020-12-09 16:12 UTC by hliashchuk

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2020-12-10 10:17 UTC, Redwene requested changes

2020-12-10 10:17 UTC, Redwene commented on main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
> +            "description": ""
you have to use the jars from the distribution.

2020-12-10 10:20 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
> +            "description": ""
this is a limitation actually, just like for cdh6x template, we need a new feature from TUP to be able to parameterize in the tempalte the version in which the json is generated, otherwise you apply 7.1.1 libs to any CDP version ...

2020-12-10 11:03 UTC, Redwene submitted a review, later dismissed
lgtm

2020-12-31 10:09 UTC, sponomarova approved these changes
looks good

2021-01-04 14:23 UTC, Redwene approved these changes
lgtm

2021-01-04 15:03 UTC, closed without merging