fix(TBD-12252): fix DynamoDB with dbr73
Talend/tbd-studio-se pull request #1909
Opened 2021-03-15 10:03 UTC by AlixMetivier

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-03-15 10:13 UTC, firefryy approved these changes
lgtm

2021-03-15 10:24 UTC, cbadillo1603 approved these changes
reviewed

2021-03-15 10:25 UTC, lbourgeois requested changes

2021-03-15 10:25 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/DBR73xDistribution.java
> +        ), DBR73xSnowflakeNodeModuleGroup.getModuleGroups(distribution, version));
```suggestion
        ), DBR73xDynamoDBNodeModuleGroup.getModuleGroups(distribution, version));
```

2021-03-15 10:25 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/DBR73xDistribution.java
> +        ), DBR73xSnowflakeNodeModuleGroup.getModuleGroups(distribution, version));
Same change also needed below

2021-03-15 10:27 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/DBR73xDistribution.java
> +        ), DBR73xSnowflakeNodeModuleGroup.getModuleGroups(distribution, version));
absolutely ! but its weird because I don't reproduce the original issue even with that in my code, will change but thats curious

2021-03-15 11:09 UTC, lbourgeois approved these changes
LGTM

2021-03-15 11:10 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/DBR73xDistribution.java
> +        ), DBR73xSnowflakeNodeModuleGroup.getModuleGroups(distribution, version));
Indeed that's strange it is harmless on your side

2021-03-16 14:51 UTC, cbadillo1603 approved these changes
reviewed

2021-03-16 15:27 UTC, firefryy approved these changes
lgtm

2021-03-16 15:27 UTC, merged