fix(TBD-12079):Support Cluster Policy for Databricks transient clusters
Talend/tbd-studio-se pull request #1930
Opened 2021-03-26 10:08 UTC by cbadillo1603

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-03-31 11:21 UTC, hliashchuk commented on main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
>              id="talend-bigdata-launcher-databricks-2.0.14"
I guess you forgot change the number in id?

2021-03-31 11:26 UTC, cbadillo1603 commented on main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
>              id="talend-bigdata-launcher-databricks-2.0.14"
Yes I'll update it

2021-03-31 11:34 UTC, hliashchuk submitted a review, later dismissed

2021-03-31 13:16 UTC, hliashchuk requested changes

2021-03-31 13:16 UTC, hliashchuk commented on main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
> +<<<<<<< HEAD
Bad conflicts resolving :)

2021-03-31 14:47 UTC, hliashchuk commented
the main/plugins/org.talend.libraries.*/.project files don't belong here, I guess

2021-03-31 14:48 UTC, hliashchuk commented
otherwise lgtm

2021-04-01 07:29 UTC, cbadillo1603 commented
Changes done, please review.

2021-04-01 10:17 UTC, hliashchuk approved these changes

2021-04-06 12:48 UTC, lbourgeois reviewed
I would have moved to 2.1.0 as it is a new functionality and to follow https://semver.org/

2021-04-07 13:09 UTC, AlixMetivier approved these changes

2021-04-07 14:54 UTC, lbourgeois approved these changes
LGTM

2021-04-09 11:01 UTC, merged