fix(TBD-12515): enable Job Memory Parameter for cdh 6.1.1, cdp 7.x
Talend/tbd-studio-se pull request #2011
Opened 2021-05-18 13:18 UTC by sponomarova

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-05-26 09:57 UTC, cbadillo1603 requested changes

2021-05-26 09:57 UTC, cbadillo1603 commented on main/plugins/org.talend.designer.components.bigdata/components/templates/Sqoop/GetConfig.javajet
> +	if((isCustom && useYarn) || (!isCustom && isHadoop2) || (!isCustom && isHadoop3)) {
please pull the latest changes in maintenance/7.3 I just committed a change including a similar change.

2021-05-27 07:42 UTC, mtuhai commented on main/plugins/org.talend.designer.components.bigdata/components/templates/Sqoop/GetConfig.javajet
> +	if((isCustom && useYarn) || (!isCustom && isHadoop2) || (!isCustom && isHadoop3)) {
Done

2021-05-27 08:46 UTC, lbourgeois approved these changes

2021-05-27 09:11 UTC, cbadillo1603 approved these changes
reviewed

2021-06-01 07:48 UTC, merged