fix(TBD-12577) removing old HDPs in master
Talend/tbd-studio-se pull request #2049
Opened 2021-06-24 07:25 UTC by mtuhai

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-06-24 07:41 UTC, sponomarova requested changes
1. I though hdp3x will be removed on master. Right?
2. Please fix unit tests. 
3. Please do clean-up in studio-full-master repository.

2021-07-02 10:45 UTC, sponomarova commented
> 1. I though hdp3x will be removed on master. Right?
> 2. Please fix unit tests.
> 3. Please do clean-up in studio-full-master repository.

Realized that remark #1 is not valid but #2 and #3 remain. Need to be fixed.

2021-07-12 09:37 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp3xxTemplate.json
> +  "baseVersion": "3.1.0",
Why do we need this change ?

2021-07-12 09:37 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.hdpx/src/org/talend/hadoop/distribution/hdpx/DynamicHDPDistribution.java
> +        // templateIds.add(HDP2xxDistributionTemplate.TEMPLATE_ID);
To be removed

2021-07-12 09:37 UTC, lbourgeois commented on test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
> +                "MapR", "Microsoft HD Insight", "Qubole"}, hadoopDistributionsDisplay);
No clear why we don't have HortonWorks anymore as we still have HDP 3 in Studio

2021-07-12 09:37 UTC, lbourgeois commented on test/plugins/org.talend.repository.hadoopcluster.test/src/main/java/org/talend/repository/hadoopcluster/conf/RetrieveLocalConfsServiceTest.java
> +//    static IRetrieveConfsService confsService;
To be cleaned + same on other commented lined

2021-07-16 10:42 UTC, closed without merging

2021-07-16 10:43 UTC, sponomarova commented
Needed changed will be done in scope of:
https://github.com/Talend/tbd-studio-se/pull/2073