fix(TBD-12577): hdp 2.5/2.6 removed
Talend/tbd-studio-se pull request #2073
Opened 2021-07-13 23:16 UTC by mtuhai

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-07-16 10:36 UTC, sponomarova requested changes

2021-07-16 10:36 UTC, sponomarova commented on test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
> -    public void testHortonWorksDistribution() {
Since we still have HDP 3.1.4, it seems to me that `public void testHortonWorksDistribution() {`
cannot be completely removed. 
Requires replace HPD 2.5, 2.6 versions to HDP 3.1.
@mtuhai , could you please correct that?

2021-07-16 10:42 UTC, sponomarova requested changes

2021-07-16 10:42 UTC, sponomarova commented on main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp3xxTemplate.json
> +  "baseVersion": "3.1.0",
No clear, why "baseVersion" was changed? 
@mtuhai , could you please provide some details?

2021-07-26 14:45 UTC, mtuhai commented on main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp3xxTemplate.json
> +  "baseVersion": "3.1.0",
https://talend.slack.com/archives/C025BFBV3EK/p1624445652008500

master: indeed remove like hdp 3.0 and before (we keep hdp 3.1.0 !!)

2021-07-26 14:47 UTC, sponomarova approved these changes

2021-07-26 14:48 UTC, mtuhai commented on test/plugins/org.talend.hadoop.distribution.test/src/org/talend/hadoop/distribution/test/helper/HadoopDistributionsHelperTest.java
> -    public void testHortonWorksDistribution() {
This test relates only to static distros. HDP 3.1 exists only dynamic

2021-07-28 06:54 UTC, firefryy approved these changes
lgtm

2021-07-28 06:59 UTC, merged