fix(TBD-1283): derby upgraded to 10.12.1.1, json-smart to 2.4.7
Talend/tbd-studio-se pull request #2105
Opened 2021-07-21 22:31 UTC by mtuhai

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-07-22 08:25 UTC, lbourgeois approved these changes
Some old plugins from old distros not even displayed anymore in the Studio could have been removed instead of updating them.

2021-07-26 13:41 UTC, AlixMetivier submitted a review, later dismissed
those plugins will be deprecated / removed, lgtm but might not be needed ?

2021-07-26 14:06 UTC, cbadillo1603 submitted a review, later dismissed
reviewed

2021-08-17 09:29 UTC, nrousseau requested changes

2021-08-17 09:29 UTC, nrousseau commented on main/plugins/org.talend.hadoop.distribution.emr450/plugin.xml
> +<<<<<<< HEAD
conflict to resolve

2021-08-18 06:37 UTC, nrousseau approved these changes

2021-08-18 07:23 UTC, firefryy approved these changes
lgtm

2021-08-18 07:29 UTC, merged

2021-08-18 09:47 UTC, firefryy reviewed
lgtm