feat(TUP-31489): add maven repo plugins into component features
Talend/tbd-studio-se pull request #2123
Opened 2021-08-02 07:19 UTC by bhe-talendbj

**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TUP-31489

**What is the new behavior?**
Add maven repo plugins into components feature

**Other information**:

2021-08-08 02:52 UTC, nrousseau requested changes

2021-08-08 02:52 UTC, nrousseau commented on main/features/org.talend.studio.components.bd.cosmosdb.feature/feature.xml
> +   <plugin id="org.talend.designer.maven.repo.tck" download-size="0" install-size="0" version="0.0.0" unpack="true"/>
requires / not include

2021-08-09 02:01 UTC, bhe-talendbj commented on main/features/org.talend.studio.components.bd.cosmosdb.feature/feature.xml
> +   <plugin id="org.talend.designer.maven.repo.tck" download-size="0" install-size="0" version="0.0.0" unpack="true"/>
Done

2021-08-09 10:13 UTC, nrousseau approved these changes

2021-08-09 13:19 UTC, merged