feat(TBD-12139): Support Synapse
Talend/tbd-studio-se pull request #2148
Opened 2021-08-11 15:40 UTC by sponomarova

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-08-11 15:47 UTC, AlixMetivier approved these changes

2021-08-11 15:49 UTC, AlixMetivier requested changes

2021-08-11 15:49 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.synapse/META-INF/MANIFEST.MF
> +Bundle-Version: 7.3.1.qualifier
need to change those version to  8.0.1.qualifier

2021-08-11 15:49 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.synapse/pom.xml
> +    <version>7.3.1-PATCH</version>
need to change that version

2021-08-11 15:49 UTC, AlixMetivier commented on test/plugins/org.talend.hadoop.distribution.synapse.test/META-INF/MANIFEST.MF
> +Bundle-Version: 7.3.1.qualifier
need to change

2021-08-11 15:49 UTC, AlixMetivier commented on test/plugins/org.talend.hadoop.distribution.synapse.test/pom.xml
> +        <version>7.3.1-PATCH</version>
need to be changed

2021-08-11 15:54 UTC, sponomarova commented on test/plugins/org.talend.hadoop.distribution.synapse.test/META-INF/MANIFEST.MF
> +Bundle-Version: 7.3.1.qualifier
Done

2021-08-11 15:55 UTC, AlixMetivier approved these changes

2021-08-11 17:44 UTC, cbadillo1603 approved these changes
reviewed

2021-08-12 07:25 UTC, AlixMetivier approved these changes

2021-08-12 07:31 UTC, merged