Dchmyga/tdi 46441 update cassandra driver
Talend/tbd-studio-se pull request #2244
Opened 2021-10-05 08:48 UTC by chmyga

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:
https://jira.talendforge.org/browse/TDI-46441

2022-01-07 08:12 UTC, clesaec approved these changes
Should be clearer with something like : 
```java
interface CassandraSession {
    ResultSet execute(String request);
    void close();
}

class CassandraSessionV4 implements  CassandraSession {
    public CassandraSessionV4(Map<String, Object> globalMap) { ...}
    ...
}

class CassandraSessionV3  implements  CassandraSession {
    public CassandraSessionV3(Map<String, Object> globalMap) { ...}
    ...
}
```
At start of tCassandraInput_datastax_begin.javajet (or tCassandraInput_begin.javajet) but that's OK for Javajet ....

2022-03-07 08:44 UTC, wwang-talend requested changes

2022-03-07 08:44 UTC, wwang-talend commented on main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
> +				<IMPORT MODULE="netty-common-4.1.60.Final.jar"
please align version to 4.1.68.Final

2022-03-07 20:45 UTC, dmytro-sylaiev commented on main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
> +				<IMPORT MODULE="netty-common-4.1.60.Final.jar"
Done

2022-03-10 10:12 UTC, jzhao-talend approved these changes
LGTM

2022-03-10 10:14 UTC, wwang-talend approved these changes

2022-03-10 10:43 UTC, merged