fix(TBD-13175): EMR 6.2 fails when job contains tDatamasking component
Talend/tbd-studio-se pull request #2277
Opened 2021-10-20 11:52 UTC by sponomarova

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-11-09 07:33 UTC, AlixMetivier requested changes

2021-11-09 07:33 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml
> +F
typo

2021-11-18 07:21 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml
> +          mvn_uri="mvn:org.apache.hive/hive-exec/3.1.2"/>
changing this does not lead to issues with the commons-lang3 that is inside default hive exec ?

2021-11-18 08:12 UTC, cbadillo1603 commented on main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml
> +          mvn_uri="mvn:org.apache.hive/hive-exec/3.1.2"/>
Indeed, this tlnd-0 jar was created to remove the commons-lang3 as it was throwing issues in some jobs.

2021-11-19 14:47 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml
> +          mvn_uri="mvn:org.apache.hive/hive-exec/3.1.2"/>
Indeed this one brings the conflict on commons-lang3. I tried to use the -amzn-2 from cluster but it has other issues. Finlly I figured out that we have to use the the [3.1.2-core](https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.2/hive-exec-3.1.2-core.jar) which does not shade anything

2021-11-19 14:58 UTC, cbadillo1603 submitted a review, later dismissed
reviewed

2021-11-19 14:59 UTC, cbadillo1603 commented on main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml
> +          id="hive-llap-common-2.3.7.jar" name="hive-llap-common-2.3.7.jar"
I approved, but also got a doubt about the version of this jar. Could you confirm this is the expected one.

2021-11-19 16:08 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr62x/plugin.xml
> +          id="hive-llap-common-2.3.7.jar" name="hive-llap-common-2.3.7.jar"
No it isn't. Forgot to update it

2021-11-25 08:25 UTC, cbadillo1603 approved these changes
reviewed

2021-11-25 08:44 UTC, AlixMetivier approved these changes

2021-11-25 08:59 UTC, merged