feat(TDI-46430): Kafka Input Output Avro support
Talend/tbd-studio-se pull request #2332
Opened 2021-12-06 09:46 UTC by olhava

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2021-12-06 14:14 UTC, Tanya5091 approved these changes
LGTM

2021-12-06 14:41 UTC, sponomarova requested changes

2021-12-06 14:41 UTC, sponomarova commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
> -	 <%=cid%>_kafkaProperties.put("ssl.truststore.type", <%=tSetKeystoreUtil.getTrustStoreType()%>);
why ssl settings were removed from Kafka 0.10.0.x ?

2021-12-06 14:41 UTC, sponomarova commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_begin_0.9.0.x.javajet
> -	 	<%=cid%>_kafkaProperties.put("ssl.keystore.type", <%=tSetKeystoreUtil.getKeyStoreType()%>);
the same question about ssl. Why is this change done? 
Sorry, maybe I just don't get any idea.

2021-12-06 14:41 UTC, sponomarova commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_begin_0.9.0.x.javajet
> -	<%=cid%>_kafkaProperties.put("sasl.kerberos.service.name", <%=tKafkaInputUtil.getKrbServiceName()%>);
Please, explain this change. Was this property moved somewhere or not needed any more for some reasons?

2021-12-06 15:49 UTC, olhava commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
> -	 <%=cid%>_kafkaProperties.put("ssl.truststore.type", <%=tSetKeystoreUtil.getTrustStoreType()%>);
Setup of these properties is moved to _util.javajet so that it would be possible to override them by advanced settings if necessary
Please see https://github.com/Talend/tbd-studio-se/pull/2332/files#diff-7a3781dde8a8b47c3b3ab38beb96f642e37bfceb91d01ed10f8b1708dff8c713R213

Related request: TDI-47148

2021-12-06 16:06 UTC, sponomarova commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
> -	 <%=cid%>_kafkaProperties.put("ssl.truststore.type", <%=tSetKeystoreUtil.getTrustStoreType()%>);
Was ssl re-tested after this change?

2021-12-06 16:22 UTC, olhava commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
> -	 <%=cid%>_kafkaProperties.put("ssl.truststore.type", <%=tSetKeystoreUtil.getTrustStoreType()%>);
It is in the test scope.
PR is not going to be merged until validation is done.

2021-12-08 08:59 UTC, olhava commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_begin_0.9.0.x.javajet
> -	 	<%=cid%>_kafkaProperties.put("ssl.keystore.type", <%=tSetKeystoreUtil.getKeyStoreType()%>);
Please see https://github.com/Talend/tbd-studio-se/pull/2332/files#diff-92b3e2bc1d5c68371ed9e1d398393ba8ffac419c6883f7ff54e528d9b7c2a354R294

2021-12-08 09:00 UTC, olhava commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_begin_0.9.0.x.javajet
> -	<%=cid%>_kafkaProperties.put("sasl.kerberos.service.name", <%=tKafkaInputUtil.getKrbServiceName()%>);
Please see https://github.com/Talend/tbd-studio-se/pull/2332/files#diff-92b3e2bc1d5c68371ed9e1d398393ba8ffac419c6883f7ff54e528d9b7c2a354R294

2021-12-08 09:32 UTC, ypiel-talend reviewed
Questions about hardcoded versions

2021-12-08 09:32 UTC, ypiel-talend commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_util.javajet
> +        if (!isKafkaVersion("KAFKA_0_8_2_0")) {
Specific code for KAFKA_0_8_2_0 of should also be executed for next/future versions ?

2021-12-08 09:32 UTC, ypiel-talend commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_util.javajet
> +        if (useSchemaRegistry() && useProducerRecord() && isKafkaVersion("KAFKA_2_2_1")) {
Dedicated code for KAFKA_2_2_1 or should be ok for next versions ?

2021-12-08 09:48 UTC, lbourgeois commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_java.xml
> +		<PARAMETER NAME="USE_SCHEMA_REGISTRY" FIELD="CHECK" NUM_ROW="60"
For my understanding, is it needed to support Avro or an addition to original feature scope ?

2021-12-08 12:08 UTC, olhava commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_util.javajet
> +        if (!isKafkaVersion("KAFKA_0_8_2_0")) {
This code previously was used for all kafka vesrsion except of KAFKA_0_8_2_0

2021-12-08 16:25 UTC, olhava commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_java.xml
> +		<PARAMETER NAME="USE_SCHEMA_REGISTRY" FIELD="CHECK" NUM_ROW="60"
These properties are for the schema registry configuration for the case when Avro schema is retrieved dynamically.

2021-12-09 09:40 UTC, ypiel-talend approved these changes
LGTM

2021-12-09 09:41 UTC, ypiel-talend approved these changes
LGTM

2021-12-09 10:45 UTC, olhava commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
> -	 <%=cid%>_kafkaProperties.put("ssl.truststore.type", <%=tSetKeystoreUtil.getTrustStoreType()%>);
@sponomarova can we mark these requested changes as resolved from your side and proceed with the validation?
Please let me know if there is anything else that needs to be clarified.

2021-12-09 10:48 UTC, sponomarova commented on main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
> -	 <%=cid%>_kafkaProperties.put("ssl.truststore.type", <%=tSetKeystoreUtil.getTrustStoreType()%>);
Thanks for provided details. Conversation can be resolved.

2021-12-09 11:07 UTC, lbourgeois approved these changes
LGTM

2021-12-09 15:43 UTC, olhava commented
Changes are duplicated to the new branch to fix the blocked merge:
https://github.com/Talend/tbd-studio-se/pull/2342

2021-12-09 15:44 UTC, closed without merging