Fix/tbd 13622
Talend/tbd-studio-se pull request #2643
Opened 2022-04-27 10:10 UTC by sanulich

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2022-04-27 10:23 UTC, AlixMetivier commented on main/plugins/org.talend.hadoop.distribution.emr5290/src/main/java/org/talend/hadoop/distribution/emr5290/modulegroup/EMR5290HiveOnSparkModuleGroup.java
> +        hs.add(new DistributionModuleGroup(EMR5290Constant.SPARK_HIVE_TEZ_MRREQUIRED_MODULE_GROUP.getModuleName(), true));
true here means that you will upload the libraries to HDFS, maybe you want to make it false by default ?

2022-04-28 06:33 UTC, sanulich commented on main/plugins/org.talend.hadoop.distribution.emr5290/src/main/java/org/talend/hadoop/distribution/emr5290/modulegroup/EMR5290HiveOnSparkModuleGroup.java
> +        hs.add(new DistributionModuleGroup(EMR5290Constant.SPARK_HIVE_TEZ_MRREQUIRED_MODULE_GROUP.getModuleName(), true));
no, I need this files in the HDFS.

2022-04-29 08:21 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +        	mvn_uri="mvn:org.talend.libraries/hadoop-lzo-0.4.19/6.0.0"/>
Long time ago org.talend.libraries was used everywhere (I don't konw exactly why) but now we try to use official group.

2022-04-29 08:21 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +        	mvn_uri="mvn:org.talend.libraries/hadoop-lzo-0.4.19/6.0.0"/>
```suggestion
        	mvn_uri="mvn:com.hadoop.gplcompression/hadoop-lzo/0.4.19"/>
```

2022-04-29 08:21 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +        <!-- Spark Hive Tez group -->
This part of the fix is not in original TBD-13622 scope right ?

2022-04-29 08:24 UTC, sanulich commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +        <!-- Spark Hive Tez group -->
It's original scope. It's about second exception, that was write in the ticket comment.

2022-04-29 12:24 UTC, lbourgeois commented on main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
> +        <!-- Spark Hive Tez group -->
Ok I thougth this issue was on Universal only not with the plain dedicated emr529 plugin

2022-04-29 12:25 UTC, lbourgeois requested changes
Small change on a maven group

2022-05-05 07:13 UTC, lbourgeois approved these changes
LGTM

2022-05-05 07:23 UTC, merged