feat(TBD-13986): upgrafe hadoop to 3.2.3 for Universal
Talend/tbd-studio-se pull request #2831
Opened 2022-07-29 08:19 UTC by sanulich

2022-07-29 09:16 UTC, lbourgeois submitted a review, later dismissed
LGTM

2022-08-11 08:48 UTC, AlixMetivier requested changes
one small issue that was already here but could be fixed

2022-08-11 08:48 UTC, AlixMetivier commented on main/plugins/org.talend.spark.distribution.spark24x/plugin.xml
> +	        <libraryNeeded context="plugin:org.talend.spark.distribution.spark24x" id="commons-pool2-2.9.0.jar" name="commons-pool2-2.9.0.jar" mvn_uri="mvn:org.apache.hadoop/hadoop-mapreduce-client-shuf
mvn uri is wrong here

2022-08-11 08:48 UTC, sponomarova submitted a review, later dismissed

2022-08-11 09:18 UTC, sponomarova approved these changes

2022-08-11 09:20 UTC, AlixMetivier approved these changes

2022-08-11 09:20 UTC, merged