fix(TBD-15244):'Check Services' button in metadata should not be visi…
Talend/tbd-studio-se pull request #3352
Opened 2023-07-05 15:06 UTC by dicarcab

…ble in Synapse

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2023-07-05 16:14 UTC, lbourgeois commented on main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
> +            }
```suggestion                checkServicesBtn.setVisible(!"synapse".contentEquals(sparkModeLabelName.toLowerCase()));
```
And I would move it at the end of the block to keep groups related code together.

2023-07-06 06:34 UTC, sponomarova requested changes

2023-07-06 06:34 UTC, sponomarova commented on main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
> +                checkServicesBtn.setVisible(false);
Wondering why it's only disabled for synapse. 
As far as I understand "check services" button should be only enabled for "yarn cluster" mode in universal and disabled for all the rest. Can it be corrected? 

Maybe I did bad description in this jira. Sorry.

2023-07-06 07:03 UTC, dicarcab commented on main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
> +                checkServicesBtn.setVisible(false);
Ok I will update this but just to be clear the idea is that the check service button be only visible in yarn cluster for universal ?

2023-07-06 07:04 UTC, dicarcab commented on main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
> +            }
will do it. And yes dont know why I write the if condition like i did

2023-07-06 07:16 UTC, sponomarova commented on main/plugins/org.talend.repository.hadoopcluster/src/org/talend/repository/hadoopcluster/ui/StandardHCInfoForm.java
> +                checkServicesBtn.setVisible(false);
yes, that's the idea. This option doesn't make a lot of sense for other spark modes like dataproc or HDI or CDE, etc

2023-07-06 12:21 UTC, sponomarova approved these changes

2023-07-06 15:04 UTC, merged