fix(TBD-15781): Add "Impala" item in the combo list of the Impala Driver
Talend/tbd-studio-se pull request #3538
Opened 2023-11-01 03:15 UTC by zshen-talend

**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Unit tests for the Java changes have been added (for bug fixes / features) ?
- [ ] TUJ for the JavaJet changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The new code does not introduce new technical issues

**What is the current behavior?** (You can also link to an open issue here)
tImpala* components miss "impala" item in the combo list of impala driver when choose universal spark3.1.x

**What is the new behavior?**
tImpala* components take "impala" item in the combo list of impala driver when choose universal spark3.1.x

**BREAKING CHANGE**

If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.

**Other information**:

2023-11-01 07:47 UTC, sanulich approved these changes
LGFM

2023-11-09 10:44 UTC, sanulich requested changes

2023-11-09 10:44 UTC, sanulich commented on main/plugins/org.talend.spark.distribution.spark31x/plugin.xml
> +			<library id="metrics-core-3.1.5.jar"/>
could you please check if it possible to use metrics-core-4.1.1.jar. If we leave as it is, we would have two different version metrics-core library in one job. we should avoid this

2023-11-09 11:33 UTC, zshen-talend commented on main/plugins/org.talend.spark.distribution.spark31x/plugin.xml
> +			<library id="metrics-core-3.1.5.jar"/>
Yes, It is worked too. I modify it

2023-11-13 06:56 UTC, sanulich approved these changes

2023-11-13 06:57 UTC, merged